version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5445:5432"

    volumes:
      - sport-tta-bot-data:/var/lib/postgresql/data

    networks:
      - sport-tta-bot-network

volumes:
  sport-tta-bot-data:

networks:
  sport-tta-bot-network:
    driver: bridge